### ISSUE TITLE
Game Crashes on 2.3.3

### ISSUE THREAD

**Issue by Reycko** [mchorse/mclib#30]
Yeah i got this problem and i am askking if it's normal or not

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from McLib (mclib)
EXIT CODE: -1"

You may need the crash report so here it is: https://pastebin.com/raw/bSM9tvCd

**Comment by mchorse** [comment]
You have incompatible versions of my mods. Check [compatibility table](https://github.com/mchorse/mclib/wiki/Compatibility-table-of-McHorse's-mods). 

Also, just in case, if you were trying to get my Chameleon mod (animated Blockbench models), you downloaded wrong mod. The downloads are [here](https://www.curseforge.com/minecraft/mc-mods/chameleon-morph/files/3372617). You'll also need [GeckoLib 3.0 beta7](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3197366) (it's Chameleon's dependency).

**Comment by Reycko** [comment]
Thank you for your help @mchorse !
