### ISSUE TITLE
Please support Avaritia mod's armor display

### ISSUE THREAD

**Issue by axin0452** [mchorse/mclib#5]
Emoticons mod good
Can you support Avaritia mod's armor display
![image](https://user-images.githubusercontent.com/39695561/67915545-4cb0ca00-fbce-11e9-836f-70737e872823.png)

**Comment by mchorse** [comment]
If you haven't read the FAQ, here is a copy paste for lazy:

> **Q: Can you add support with mod X?**
> A: No, I won't add support with any other mods. This mod was made for fun, I don't want to turn it into my job.
