### ISSUE TITLE
Client crash 1.12.2

### ISSUE THREAD

**Issue by SeagalKru** [mchorse/mclib#51]
(Google translation)
Hello!
While playing on the server, the client crashes (your mods are not installed on the server).
[crash-2023-05-11_14.54.17-client.txt](https://github.com/mchorse/mclib/files/11451818/crash-2023-05-11_14.54.17-client.txt)

**Comment by Chryfi** [comment]
You have like 200 mods installed or so. It's a mod incompatibility. You posted the same issue a few months ago.

**Comment by mchorse** [comment]
Basically, you have to remove a mod that causes this issue. We don't know which mod it is, so it's up to you to figure it out.

**Comment by SeagalKru** [comment]
(Google Translate)
Yes, yes, sorry, I remembered.
A mod that is incompatible with yours is RTM (trains).
I wrote to the developer of this mod, but he does not answer and, if I am not mistaken, my messages are sent to spam. So I can not convey to him the problem of incompatibility between your and his mods. Unfortunately.
Once again I apologize for my forgetfulness!

**Comment by mchorse** [comment]
That sucks, but there is nothing can be done to fix this issue on my mods' side. Thanks for letting us know which mod it was! 👍
