### ISSUE TITLE
The action synchronization between players fails in group server

### ISSUE THREAD

**Issue by axin0452** [mchorse/mclib#6]
The action synchronization between players fails in group server

waterfall-295
spongeforge-1.12.2-2838-7.1.7-RC3886

**Comment by mchorse** [comment]
What? 🤔

**Comment by axin0452** [comment]
My English is not very good. Please read it patiently

If player - > sever emoticons + mclib is OK

if  player -> waterfall295 -> spongevanilla（lobby）-> spongeforge(server)  emoticons+mclib  is Not effective，Players and players can't see each other's actions

**Comment by mchorse** [comment]
Ah, yeah, it's a problem on SpongeForge's side. This issue was already reported to SpongeForge, but it's on low priority. See [this](https://github.com/SpongePowered/SpongeForge/issues/2958).

**Comment by Jecvay** [comment]
> Ah, yeah, it's a problem on SpongeForge's side. This issue was already reported to SpongeForge, but it's on low priority. See [this](https://github.com/SpongePowered/SpongeForge/issues/2958).

this is not a same problem
@axin0452 's problem is caused by bungeecord( waterfall295 ) without which is perform nice.

**Comment by mchorse** [comment]
Have you tried with regular bungeecord?

**Comment by axin0452** [comment]
https://github.com/PaperMC/Waterfall/issues/431

Bungeecord cannot connect to mod server

@mchorse
